# Root of qwed-verification
language: en-US
reviews:
  auto_review:
    enabled: true
  path_instructions:
    - path: "**/*.py"
      instructions: |
        You are a security auditor for QWED (Deterministic AI Verification).
        
        CRITICAL RULES:
        1. NO NON-DETERMINISM: Flag usage of 'random', 'uuid.uuid4()', or 'datetime.now()' inside verification logic. Inputs must be injected.
        2. SYMBOLIC MATH: Flag floating-point math (e.g., 0.1 + 0.2). Suggest 'decimal.Decimal' or 'sympy'.
        3. SECURITY: Block 'eval()', 'exec()', or 'subprocess' unless wrapped in CodeGuard.
        4. IRAC: Ensure new legal guards follow Issue-Rule-Application-Conclusion structure [Source: MSLR].
