"""
Multi-Language Code Verifier: Security Analysis for Code Snippets.

Supports: Python, JavaScript/TypeScript, Java, Go, SQL
Provides static analysis and security verification for code generated by LLMs.
"""

from typing import Dict, Any, List, Optional, ClassVar
from dataclasses import dataclass, field
import ast
import hashlib
import re

from .diagnostics import DiagnosticResult

from .verification_context import VerificationContextDocument


@dataclass
class SecurityIssue:
    """A detected security issue."""
    severity: str  # "CRITICAL", "WARNING", "INFO"
    issue_type: str
    pattern: str
    description: str
    line_number: Optional[int] = None
    recommendation: Optional[str] = None


@dataclass
class VerificationResult:
    """Result of code verification."""
    is_safe: bool
    status: str  # "SAFE", "REVIEW", "BLOCKED"
    language: str
    issues: List[SecurityIssue] = field(default_factory=list)
    critical_count: int = 0
    warning_count: int = 0
    info_count: int = 0


CONSTRAINT_UNSUPPORTED_LANGUAGE = "code_verifier.unsupported_language"
CONSTRAINT_EXECUTION_ERROR = "code_verifier.execution_error"
CONSTRAINT_CODE_SAFE = "code_verifier.code_safe"
CONSTRAINT_CODE_UNSAFE = "code_verifier.code_unsafe"
CONSTRAINT_EMPTY_BATCH = "code_verifier.empty_batch"
CONSTRAINT_BATCH_BLOCKED = "code_verifier.batch_blocked"




class CodeVerifier:
    """
    Multi-Language Code Security Verifier.
    
    Engine 6 of QWED's verification architecture.
    
    Supported Languages:
    - Python: eval, exec, pickle, weak crypto, subprocess
    - JavaScript/TypeScript: eval, innerHTML, XSS, prototype pollution
    - Java: SQL injection, deserialization, SSRF
    - Go: command injection, path traversal
    - SQL: injection patterns (delegated to SQLVerifier)

    Attributes:
        supported_languages (List[str]): List of supported programming languages.
    """
    
    # =========================================================================
    # Python Patterns
    # =========================================================================
    
    PYTHON_CRITICAL = {
        "eval": "Remote code execution via eval()",
        "exec": "Remote code execution via exec()",
        "compile": "Dynamic code compilation",
        "__import__": "Dynamic module import",
        "pickle.loads": "Insecure deserialization",
        "pickle.load": "Insecure deserialization",
        "yaml.unsafe_load": "Insecure YAML parsing",
        "yaml.load": "Potential insecure YAML (use safe_load)",
        "getattr": "Dynamic attribute access",
        "setattr": "Dynamic attribute modification",
    }

    PYTHON_CRITICAL_REGEX: ClassVar[tuple[Dict[str, str], ...]] = (
        {
            "pattern": (
                r"subprocess\.(?:run|Popen|call|check_output)\s*\(.*?"
                r"(?:curl|wget).*?(?:\||;|&&).*?(?:bash|sh).*?shell\s*=\s*True"
            ),
            "issue_type": "remote_code_execution",
            "description": "Remote code execution via shell=True with curl/wget pipe to shell.",
            "recommendation": "Never execute remote pipe commands with shell=True.",
        },
        {
            "pattern": (
                r"subprocess\.(?:run|Popen|call|check_output)\s*\(.*?"
                r"(?:curl|wget).*?(?:\||;|&&).*?(?:bash|sh)"
            ),
            "issue_type": "remote_code_execution",
            "description": "Suspicious curl/wget pipe-to-shell pattern detected (heuristic).",
            "recommendation": "Never pipe remote content directly into a shell.",
        },
    )
    
    PYTHON_WARNING = {
        "open": "File operation (verify path source)",
        "os.system": "Shell command execution",
        "os.popen": "Shell command execution",
        "subprocess.call": "Subprocess execution",
        "subprocess.Popen": "Subprocess execution",
        "subprocess.run": "Subprocess execution",
        "shutil.rmtree": "Recursive directory deletion",
        "requests.get": "HTTP request (verify URL source)",
        "requests.post": "HTTP request (verify URL source)",
        "socket.socket": "Raw socket access",
    }
    
    PYTHON_WEAK_CRYPTO = {
        "hashlib.md5": "MD5 is cryptographically broken",
        "hashlib.sha1": "SHA1 is cryptographically weak",
        "random.random": "Not cryptographically secure (use secrets)",
        "random.randint": "Not cryptographically secure (use secrets)",
    }
    
    PYTHON_DANGEROUS_ATTRS = {
        "__class__", "__base__", "__subclasses__", "__globals__",
        "__builtins__", "__import__", "__code__", "__dict__"
    }
    
    # =========================================================================
    # JavaScript/TypeScript Patterns
    # =========================================================================
    
    JS_CRITICAL = {
        "eval(": "Remote code execution via eval()",
        "Function(": "Dynamic function creation",
        "setTimeout(": "Dynamic code execution (if string arg)",
        "setInterval(": "Dynamic code execution (if string arg)",
        ".innerHTML": "XSS vulnerability (use textContent)",
        ".outerHTML": "XSS vulnerability",
        "document.write": "XSS vulnerability",
        "document.writeln": "XSS vulnerability",
    }
    
    JS_WARNING = {
        "dangerouslySetInnerHTML": "React XSS risk (intentional bypass)",
        "child_process.exec": "Command injection risk",
        "child_process.spawn": "Command execution (verify args)",
        "fs.readFile": "File read (verify path source)",
        "fs.writeFile": "File write (verify path source)",
        "fs.unlink": "File deletion (verify path source)",
        "require(": "Dynamic module loading (if variable)",
        "import(": "Dynamic import (if variable)",
    }
    
    JS_PROTOTYPE_POLLUTION = {
        "__proto__": "Prototype pollution vector",
        "constructor": "Prototype pollution via constructor",
        "Object.assign": "Potential prototype pollution (validate source)",
    }
    
    JS_SECRETS = {
        r"api[_-]?key\s*[=:]\s*['\"][^'\"]+['\"]": "Hardcoded API key",
        r"secret\s*[=:]\s*['\"][^'\"]+['\"]": "Hardcoded secret",
        r"password\s*[=:]\s*['\"][^'\"]+['\"]": "Hardcoded password",
        r"token\s*[=:]\s*['\"][^'\"]+['\"]": "Hardcoded token",
        r"aws_access_key": "AWS access key",
        r"aws_secret": "AWS secret key",
    }
    
    # =========================================================================
    # Java Patterns
    # =========================================================================
    
    JAVA_CRITICAL = {
        "Runtime.getRuntime().exec": "Command injection",
        "ProcessBuilder": "Command execution",
        "ObjectInputStream": "Insecure deserialization",
        "XMLDecoder": "XML deserialization attack",
        "ScriptEngine": "Script execution",
        "java.lang.reflect": "Reflection (verify necessity)",
    }
    
    JAVA_SQL_INJECTION = {
        r'\+\s*["\'][^"\']*["\']': "String concatenation in SQL",
        r'Statement\s+\w+\s*=': "Statement (use PreparedStatement)",
        r'createStatement\s*\(': "Raw statement (use PreparedStatement)",
        r'executeQuery\s*\([^"]*\+': "SQL injection via concatenation",
    }
    
    JAVA_WARNING = {
        "new URL(": "SSRF risk (validate URL source)",
        "HttpURLConnection": "HTTP request (validate URL)",
        "SSLContext": "Custom SSL (verify configuration)",
        "TrustManager": "Custom trust (potential MITM)",
        "X509Certificate": "Certificate handling",
        "File(": "File operation (validate path)",
        "FileInputStream": "File read (validate path)",
        "FileOutputStream": "File write (validate path)",
    }
    
    # =========================================================================
    # Go Patterns
    # =========================================================================
    
    GO_CRITICAL = {
        "os/exec": "Command execution",
        "exec.Command": "Command injection risk",
        "syscall.Exec": "System call execution",
        "unsafe.Pointer": "Unsafe memory operation",
    }
    
    GO_WARNING = {
        "os.Open": "File operation (validate path)",
        "os.Create": "File creation (validate path)",
        "os.Remove": "File deletion (validate path)",
        "ioutil.ReadFile": "File read (validate path)",
        "ioutil.WriteFile": "File write (validate path)",
        "http.Get": "HTTP request (validate URL)",
        "http.Post": "HTTP request (validate URL)",
        "filepath.Join": "Path joining (check for traversal)",
    }
    
    GO_SQL_INJECTION = {
        r'fmt\.Sprintf\s*\([^)]*\%': "String formatting in SQL (use params)",
        r'\+\s*"[^"]*"': "String concatenation (potential SQL injection)",
    }
    
    # =========================================================================
    # Cross-Language Secret Patterns
    # =========================================================================
    
    SECRET_PATTERNS = {
        r'AKIA[0-9A-Z]{16}': "AWS Access Key ID",
        r'[a-zA-Z0-9+/]{40}': "Potential AWS Secret Key",
        r'ghp_[a-zA-Z0-9]{36}': "GitHub Personal Access Token",
        r'gho_[a-zA-Z0-9]{36}': "GitHub OAuth Token",
        r'sk-[a-zA-Z0-9]{48}': "OpenAI API Key",
        r'xox[baprs]-[0-9a-zA-Z-]+': "Slack Token",
        r'-----BEGIN (RSA |EC )?PRIVATE KEY-----': "Private Key",
        r'eyJ[a-zA-Z0-9_-]+\.eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+': "JWT Token",
    }
    
    # =========================================================================
    # Password Context Indicators
    # =========================================================================
    
    PASSWORD_INDICATORS = {
        "password", "passwd", "pwd", "pass",
        "credential", "cred", "auth",
        "secret", "token", "key"
    }
    
    def __init__(self):
        """
        Initialize the multi-language code verifier.

        Example:
            >>> verifier = CodeVerifier()
        """
        self.supported_languages = ["python", "javascript", "typescript", "java", "go", "sql"]
        self._taint_analyzer = None  # Lazy-loaded
    
    @property
    def taint_analyzer(self):
        """Lazy-load taint analyzer for Python deep analysis."""
        if self._taint_analyzer is None:
            from .taint_analyzer import TaintAnalyzer
            self._taint_analyzer = TaintAnalyzer()
        return self._taint_analyzer
    
    def verify_code(self, code: str, language: str = "python") -> DiagnosticResult:
        """
        Verify code for security vulnerabilities.

        Returns a structured :class:`DiagnosticResult`:

        - Unsafe code (ANALYSIS flags a critical issue) → VERIFIED as-unsafe
          (``developer_fields.is_valid`` False, proof_ref bound to the analysis
          evidence). Proving a snippet is unsafe IS a successful proof, mirroring
          the SQL verifier's malicious classification (issue #253), so it is not
          BLOCKED.
        - Safe code → VERIFIED with ``is_valid`` True and proof_ref from the
          analysis evidence.
        - Unsupported language → BLOCKED (``code_verifier.unsupported_language``)
        - Internal error   → BLOCKED (``code_verifier.execution_error``)

        ``agent_message`` is agent-safe: it never leaks detection rules, rule
        IDs, or raw AST/regex output. Rule-level detail lives in
        ``developer_fields``.

        Args:
            code: The code snippet to verify.
            language: Programming language (default: "python").

        Example:
            >>> result = verifier.verify_code("eval('rm -rf /')", language="python")
            >>> print(result.developer_fields.get("is_safe"))
            False
        """
        # Normalize before the error boundary: a non-string language must
        # produce the documented BLOCKED result, not an AttributeError, so a
        # single malformed batch item cannot abort the whole batch.
        if not isinstance(language, str):
            return DiagnosticResult.blocked(
                agent_message=(
                    "Code verification could not be completed because the "
                    "specified language is not supported."
                ),
                developer_fields={
                    "constraint_id": CONSTRAINT_UNSUPPORTED_LANGUAGE,
                    "is_safe": False,
                    "is_valid": False,
                    "language": str(language),
                    "supported_languages": list(self.supported_languages),
                },
            )

        language = language.lower()

        # Map typescript to javascript
        if language == "typescript" or language == "ts":
            language = "javascript"
        if language == "js":
            language = "javascript"
        if language == "py":
            language = "python"

        if language not in self.supported_languages:
            return DiagnosticResult.blocked(
                agent_message=(
                    "Code verification could not be completed because the "
                    "specified language is not supported."
                ),
                developer_fields={
                    "constraint_id": CONSTRAINT_UNSUPPORTED_LANGUAGE,
                    "is_safe": False,
                    "is_valid": False,
                    "language": language,
                    "supported_languages": list(self.supported_languages),
                },
            )

        issues: List[SecurityIssue] = []
        try:
            # Language-specific checks
            if language == "python":
                issues.extend(self._check_python(code))
            elif language == "javascript":
                issues.extend(self._check_javascript(code))
            elif language == "java":
                issues.extend(self._check_java(code))
            elif language == "go":
                issues.extend(self._check_go(code))
            elif language == "sql":
                issues.extend(self._check_sql(code))

            # Cross-language secret detection
            issues.extend(self._check_secrets(code))
        except Exception as exc:  # noqa: BLE001 — fail-closed by design
            return DiagnosticResult.blocked(
                agent_message=(
                    "Code verification could not be completed due to an internal error."
                ),
                developer_fields={
                    "constraint_id": CONSTRAINT_EXECUTION_ERROR,
                    "is_safe": False,
                    "is_valid": False,
                    "error_type": type(exc).__name__,
                    "language": language,
                },
            )

        # Calculate counts
        critical_count = sum(1 for i in issues if i.severity == "CRITICAL")
        warning_count = sum(1 for i in issues if i.severity == "WARNING")
        info_count = sum(1 for i in issues if i.severity == "INFO")

        is_safe = critical_count == 0
        is_valid = is_safe
        constraint_id = CONSTRAINT_CODE_SAFE if is_safe else CONSTRAINT_CODE_UNSAFE

        developer_fields: Dict[str, Any] = {
            "constraint_id": constraint_id,
            "is_safe": is_safe,
            "is_valid": is_valid,
            "language": language,
            "issues": [
                {
                    "severity": i.severity,
                    "type": i.issue_type,
                    "pattern": i.pattern,
                    "description": i.description,
                    "line_number": i.line_number,
                    "recommendation": i.recommendation,
                }
                for i in issues
            ],
            "critical_count": critical_count,
            "warning_count": warning_count,
            "info_count": info_count,
            "engine": "CodeVerifier-Pattern-Scanner",
        }

        evidence = self._build_evidence(code, language, is_safe, issues)

        if is_safe:
            agent_message = "The code passed security verification and is safe to use."
        else:
            agent_message = "The code failed security verification and is not safe to use."

        return DiagnosticResult.verified(
            agent_message=agent_message,
            developer_fields=developer_fields,
            evidence=evidence,
        )

    def _build_evidence(
        self,
        code: str,
        language: str,
        is_safe: bool,
        issues: List[SecurityIssue],
    ) -> Dict[str, Any]:
        """Build deterministic, JSON-serializable proof evidence bound to the verdict."""
        return {
            "engine": "CodeVerifier-Pattern-Scanner",
            "language": language,
            "code": code,
            "is_safe": is_safe,
            "critical_count": sum(1 for i in issues if i.severity == "CRITICAL"),
            "warning_count": sum(1 for i in issues if i.severity == "WARNING"),
            "issue_types": sorted({i.issue_type for i in issues}),
        }
    
    # =========================================================================
    # Python Checks
    # =========================================================================
    
    def _check_python(self, code: str) -> List[SecurityIssue]:
        """Check Python code for security issues."""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            # Critical functions
            for pattern, desc in self.PYTHON_CRITICAL.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="dangerous_function",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num,
                        recommendation="Remove or sandbox this operation"
                    ))
            
            # Warning functions
            for pattern, desc in self.PYTHON_WARNING.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="WARNING",
                        issue_type="context_dependent",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num,
                        recommendation="Verify input source is trusted"
                    ))
            
            # Dangerous attributes
            for attr in self.PYTHON_DANGEROUS_ATTRS:
                if attr in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="dangerous_attribute",
                        pattern=attr,
                        description=f"Dangerous attribute access: {attr}",
                        line_number=line_num
                    ))

        # Critical subprocess regex checks over full code to catch multi-line invocations.
        for rule in self.PYTHON_CRITICAL_REGEX:
            for match in re.finditer(rule["pattern"], code, re.IGNORECASE | re.DOTALL):
                line_num = code[:match.start()].count("\n") + 1
                if any(
                    i.issue_type == rule["issue_type"]
                    and i.line_number == line_num
                    for i in issues
                ):
                    continue

                issues.append(SecurityIssue(
                    severity="CRITICAL",
                    issue_type=rule["issue_type"],
                    pattern="subprocess + curl|wget pipe to shell",
                    description=rule["description"],
                    line_number=line_num,
                    recommendation=rule["recommendation"],
                ))

        # AST-based subprocess checks to catch nested expression forms that regex can miss.
        for issue in self._check_python_subprocess_ast(code):
            if any(
                i.issue_type == issue.issue_type
                and i.line_number == issue.line_number
                for i in issues
            ):
                continue
            issues.append(issue)
        
        # Weak crypto in password context
        code_lower = code.lower()
        has_password = any(p in code_lower for p in self.PASSWORD_INDICATORS)
        if has_password:
            for pattern, desc in self.PYTHON_WEAK_CRYPTO.items():
                if pattern in code:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="weak_crypto_with_password",
                        pattern=pattern,
                        description=f"{desc} - used in password context",
                        recommendation="Use bcrypt, argon2, or scrypt for passwords"
                    ))
        
        return issues

    def _check_python_subprocess_ast(self, code: str) -> List[SecurityIssue]:
        """Detect subprocess curl/wget pipe-to-shell patterns using AST."""
        try:
            tree = ast.parse(code)
        except SyntaxError:
            return []

        issues: List[SecurityIssue] = []
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue

            if not self._is_subprocess_call(node):
                continue

            issue = self._build_subprocess_pipe_issue(node)
            if issue:
                issues.append(issue)
        return issues

    def _build_subprocess_pipe_issue(self, node: ast.Call) -> SecurityIssue | None:
        """Build a subprocess pipe-to-shell issue when the command payload is dangerous."""
        command_text = self._extract_subprocess_command_text(node)
        if not self._is_pipe_to_shell_payload(command_text):
            return None

        shell_true = self._call_has_shell_true(node)
        return SecurityIssue(
            severity="CRITICAL",
            issue_type="remote_code_execution",
            pattern="subprocess + curl|wget pipe to shell",
            description=(
                "Remote code execution via shell=True with curl/wget pipe to shell."
                if shell_true
                else "Suspicious curl/wget pipe-to-shell pattern detected (heuristic)."
            ),
            line_number=getattr(node, "lineno", None),
            recommendation=(
                "Never execute remote pipe commands with shell=True."
                if shell_true
                else "Never pipe remote content directly into a shell."
            ),
        )

    def _is_pipe_to_shell_payload(self, command_text: str) -> bool:
        """Check whether command text resembles curl/wget pipe-to-shell execution."""
        if not command_text:
            return False

        command_lower = command_text.lower()
        has_downloader = "curl" in command_lower or "wget" in command_lower
        has_shell_target = "bash" in command_lower or "sh" in command_lower
        has_chain_op = "|" in command_text or ";" in command_text or "&&" in command_text
        return has_downloader and has_shell_target and has_chain_op

    def _is_subprocess_call(self, node: ast.Call) -> bool:
        """Return True when call is subprocess.run/call/Popen/check_output."""
        if not isinstance(node.func, ast.Attribute):
            return False
        if not isinstance(node.func.value, ast.Name):
            return False
        return (
            node.func.value.id == "subprocess"
            and node.func.attr in {"run", "call", "Popen", "check_output"}
        )

    def _call_has_shell_true(self, node: ast.Call) -> bool:
        """Check whether subprocess call has shell=True."""
        for kw in node.keywords:
            if kw.arg == "shell" and isinstance(kw.value, ast.Constant) and kw.value.value is True:
                return True
        return False

    def _extract_subprocess_command_text(self, node: ast.Call) -> str:
        """Best-effort extraction of command text from subprocess call first arg."""
        if not node.args:
            return ""
        return self._expr_to_text(node.args[0])

    def _expr_to_text(self, expr: ast.AST) -> str:
        """Render AST expression to text for heuristic keyword matching."""
        if isinstance(expr, ast.Constant):
            return str(expr.value)

        if isinstance(expr, ast.JoinedStr):
            parts: List[str] = []
            for value in expr.values:
                if isinstance(value, ast.Constant):
                    parts.append(str(value.value))
                else:
                    parts.append("{expr}")
            return "".join(parts)

        if isinstance(expr, (ast.List, ast.Tuple)):
            return " ".join(self._expr_to_text(item) for item in expr.elts)

        try:
            return ast.unparse(expr)
        except (AttributeError, TypeError, ValueError, RecursionError):
            return ""
    
    def verify_python_deep(self, code: str) -> DiagnosticResult:
        """
        Deep Python verification combining pattern matching with AST taint analysis.
        
        This method performs two types of analysis:
        1. Pattern-based detection (fast, catches known dangerous patterns)
        2. Taint analysis (AST-based, tracks data flow from sources to sinks)
        
        Returns a :class:`DiagnosticResult`. The combined verdict is VERIFIED
        with ``is_valid`` True only when both the pattern scan and the taint
        analysis find no unsafe findings; otherwise it is VERIFIED as-unsafe
        (``is_valid`` False). Internal failures are BLOCKED
        (``code_verifier.execution_error``).
        
        Args:
            code: Python source code to analyze.
            
        Example:
            >>> result = verifier.verify_python_deep("x = input(); eval(x)")
            >>> print(result.developer_fields.get("taint_vulnerabilities"))
        """
        # Standard pattern-based check
        pattern_result = self.verify_code(code, "python")

        # If the pattern analysis was blocked (unsupported language, internal
        # error), propagate that fail-closed result instead of misrepresenting
        # it as a VERIFIED verdict (which would bind proof to no analysis).
        if pattern_result.is_fail_closed:
            return pattern_result

        # AST-based taint analysis — an exception must block, not escape.
        try:
            taint_result = self.taint_analyzer.analyze(code)
        except Exception:  # noqa: BLE001 — fail-closed by design
            return DiagnosticResult.blocked(
                agent_message="Deep code verification failed: taint analysis unavailable.",
                developer_fields={
                    "constraint_id": CONSTRAINT_EXECUTION_ERROR,
                    "is_valid": False,
                    "is_safe": False,
                    "reason": "taint analysis failed",
                },
            )

        is_safe = (
            pattern_result.developer_fields.get("is_valid") is True
            and taint_result["is_safe"]
        )

        developer_fields: Dict[str, Any] = {
            "constraint_id": CONSTRAINT_CODE_SAFE if is_safe else CONSTRAINT_CODE_UNSAFE,
            "is_safe": is_safe,
            "is_valid": is_safe,
            "language": "python",
            "analysis_methods": ["pattern_matching", "taint_analysis"],
            # Pattern-based results
            "pattern_issues": pattern_result.developer_fields.get("issues", []),
            "pattern_critical": pattern_result.developer_fields.get("critical_count", 0),
            "pattern_warnings": pattern_result.developer_fields.get("warning_count", 0),
            # Taint analysis results
            "taint_vulnerabilities": taint_result["vulnerabilities"],
            "tainted_variables": sorted(taint_result["tainted_variables"]),
            "data_flow_sources": taint_result["sources_found"],
            "data_flow_sinks": taint_result["sinks_found"],
            # Summary
            "summary": {
                "pattern_issues_found": len(pattern_result.developer_fields.get("issues", [])),
                "taint_vulnerabilities_found": len(taint_result["vulnerabilities"]),
                "tainted_variable_count": len(taint_result["tainted_variables"]),
                "is_safe": is_safe,
            },
        }

        evidence = {
            "engine": "CodeVerifier-Deep-Scanner",
            "language": "python",
            "analysis_methods": ["pattern_matching", "taint_analysis"],
            "is_safe": is_safe,
            "pattern_is_safe": pattern_result.developer_fields.get("is_valid") is True,
            "taint_is_safe": taint_result["is_safe"],
            "pattern_issue_types": sorted(
                {
                    issue["type"]
                    for issue in pattern_result.developer_fields.get("issues", [])
                }
            ),
            "taint_vulnerabilities": [
                {
                    "severity": v.get("severity"),
                    "description": v.get("description"),
                    "source": v.get("source"),
                }
                for v in taint_result["vulnerabilities"]
            ],
        }

        if is_safe:
            agent_message = "The code passed deep security verification and is safe to use."
        else:
            agent_message = "The code failed deep security verification and is not safe to use."

        return DiagnosticResult.verified(
            agent_message=agent_message,
            developer_fields=developer_fields,
            evidence=evidence,
        )
    
    # =========================================================================
    # JavaScript/TypeScript Checks
    # =========================================================================
    
    def _check_javascript(self, code: str) -> List[SecurityIssue]:
        """Check JavaScript/TypeScript code for security issues."""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            # Critical patterns (XSS, eval)
            for pattern, desc in self.JS_CRITICAL.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="xss_or_rce",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num,
                        recommendation="Use textContent or sanitize input"
                    ))
            
            # Warning patterns
            for pattern, desc in self.JS_WARNING.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="WARNING",
                        issue_type="context_dependent",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num
                    ))
            
            # Prototype pollution
            for pattern, desc in self.JS_PROTOTYPE_POLLUTION.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="prototype_pollution",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num,
                        recommendation="Validate object keys against allowlist"
                    ))
        
        # Hardcoded secrets
        for pattern, desc in self.JS_SECRETS.items():
            matches = re.finditer(pattern, code, re.IGNORECASE)
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                issues.append(SecurityIssue(
                    severity="CRITICAL",
                    issue_type="hardcoded_secret",
                    pattern=match.group(0)[:30] + "...",
                    description=desc,
                    line_number=line_num,
                    recommendation="Use environment variables"
                ))
        
        return issues
    
    # =========================================================================
    # Java Checks
    # =========================================================================
    
    def _check_java(self, code: str) -> List[SecurityIssue]:
        """Check Java code for security issues."""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            # Critical patterns
            for pattern, desc in self.JAVA_CRITICAL.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="dangerous_operation",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num
                    ))
            
            # Warning patterns
            for pattern, desc in self.JAVA_WARNING.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="WARNING",
                        issue_type="context_dependent",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num
                    ))
        
        # SQL injection patterns (regex)
        for pattern, desc in self.JAVA_SQL_INJECTION.items():
            matches = re.finditer(pattern, code)
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                issues.append(SecurityIssue(
                    severity="CRITICAL",
                    issue_type="sql_injection",
                    pattern=match.group(0)[:50],
                    description=desc,
                    line_number=line_num,
                    recommendation="Use PreparedStatement with parameters"
                ))
        
        return issues
    
    # =========================================================================
    # Go Checks
    # =========================================================================
    
    def _check_go(self, code: str) -> List[SecurityIssue]:
        """Check Go code for security issues."""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            # Critical patterns
            for pattern, desc in self.GO_CRITICAL.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="CRITICAL",
                        issue_type="dangerous_operation",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num
                    ))
            
            # Warning patterns
            for pattern, desc in self.GO_WARNING.items():
                if pattern in line:
                    issues.append(SecurityIssue(
                        severity="WARNING",
                        issue_type="context_dependent",
                        pattern=pattern,
                        description=desc,
                        line_number=line_num
                    ))
        
        # SQL injection patterns
        for pattern, desc in self.GO_SQL_INJECTION.items():
            matches = re.finditer(pattern, code)
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                issues.append(SecurityIssue(
                    severity="CRITICAL",
                    issue_type="sql_injection",
                    pattern=match.group(0)[:50],
                    description=desc,
                    line_number=line_num,
                    recommendation="Use parameterized queries"
                ))
        
        return issues
    
    # =========================================================================
    # SQL Checks
    # =========================================================================
    
    def _check_sql(self, code: str) -> List[SecurityIssue]:
        """Check SQL for common injection patterns."""
        issues = []
        
        # Tautology patterns (1=1, 'a'='a')
        if re.search(r"1\s*=\s*1|'[^']+'\s*=\s*'[^']+'", code):
            issues.append(SecurityIssue(
                severity="CRITICAL",
                issue_type="sql_injection_tautology",
                pattern="1=1 or equivalent",
                description="Tautology detected - likely injection attempt"
            ))
        
        # Union injection
        if re.search(r"\bUNION\s+(ALL\s+)?SELECT\b", code, re.IGNORECASE):
            issues.append(SecurityIssue(
                severity="CRITICAL",
                issue_type="union_injection",
                pattern="UNION SELECT",
                description="UNION-based injection pattern"
            ))
        
        # Comment injection
        if "--" in code or "/*" in code:
            issues.append(SecurityIssue(
                severity="WARNING",
                issue_type="comment_injection",
                pattern="-- or /*",
                description="SQL comment (may indicate injection)"
            ))
        
        # Semicolon stacking
        if ";" in code and code.count(";") > 1:
            issues.append(SecurityIssue(
                severity="WARNING",
                issue_type="stacked_queries",
                pattern=";",
                description="Multiple statements (may indicate injection)"
            ))
        
        return issues
    
    # =========================================================================
    # Secret Detection (Cross-Language)
    # =========================================================================
    
    def _check_secrets(self, code: str) -> List[SecurityIssue]:
        """Check for hardcoded secrets across all languages."""
        issues = []
        
        for pattern, desc in self.SECRET_PATTERNS.items():
            matches = re.finditer(pattern, code)
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                # Mask the secret
                secret = match.group(0)
                masked = secret[:8] + "..." + secret[-4:] if len(secret) > 12 else secret[:4] + "..."
                
                issues.append(SecurityIssue(
                    severity="CRITICAL",
                    issue_type="hardcoded_secret",
                    pattern=masked,
                    description=desc,
                    line_number=line_num,
                    recommendation="Use environment variables or secret management"
                ))
        
        return issues
    
    # =========================================================================
    # Batch Verification
    # =========================================================================
    
    def verify_batch(self, snippets: List[Dict[str, str]]) -> DiagnosticResult:
        """
        Verify multiple code snippets.

        Returns a single :class:`DiagnosticResult`. Per-snippet verdicts live in
        ``developer_fields.results`` (each a serialized per-snippet
        DiagnosticResult) and ``developer_fields.summary``.

        The batch is authoritative (VERIFIED with ``proof_ref``) only when every
        snippet is safe. A batch containing any unsafe snippet returns a VERIFIED
        as-unsafe batch (``is_valid`` False) so generic consumers that admit on
        ``is_authoritative`` can never accept unsafe code.

        Args:
            snippets: List of dicts with {"code": str, "language": str}.

        Example:
            >>> batch = [{"code": "print(1)", "language": "python"}, {"code": "alert(1)", "language": "js"}]
            >>> result = verifier.verify_batch(batch)
        """
        items: List[Dict[str, Any]] = []

        for snippet in snippets:
            result = self.verify_code(
                snippet.get("code", ""),
                snippet.get("language", "python")
            )
            serialized = result.to_dict()
            serialized["language"] = snippet.get("language", "python")
            items.append(serialized)

        total = len(snippets)

        # Fail closed: an empty batch proves nothing and must not be admitted.
        if total == 0:
            return DiagnosticResult.blocked(
                agent_message="Batch code verification failed: no snippets were provided.",
                developer_fields={
                    "constraint_id": CONSTRAINT_EMPTY_BATCH,
                    "is_valid": False,
                    "is_safe": False,
                    "summary": {"total": 0, "safe": 0, "blocked": 0},
                    "results": [],
                    "engine": "CodeVerifier-Pattern-Scanner",
                },
            )

        # Fail closed: any item that could not be completed (unsupported
        # language, internal error) is BLOCKED, not VERIFIED-as-unsafe.
        for item in items:
            if item["status"] != "VERIFIED":
                return DiagnosticResult.blocked(
                    agent_message=(
                        "Batch verification blocked: some snippets could not be "
                        "analyzed; the batch is not admissible."
                    ),
                    developer_fields={
                        "constraint_id": CONSTRAINT_BATCH_BLOCKED,
                        "is_valid": False,
                        "is_safe": False,
                        "blocked_item_status": item["status"],
                        "results": items,
                        "summary": {
                            "total": total,
                            "blocked": sum(1 for it in items if it["status"] != "VERIFIED"),
                        },
                        "engine": "CodeVerifier-Pattern-Scanner",
                    },
                )

        safe = sum(1 for item in items if item["developer_fields"].get("is_valid") is True)
        blocked = total - safe
        is_safe_all = safe == total

        summary = {
            "total": total,
            "safe": safe,
            "unsafe": blocked,
            "blocked": blocked,
            "total_critical": sum(item["developer_fields"].get("critical_count", 0) for item in items),
            "total_warnings": sum(item["developer_fields"].get("warning_count", 0) for item in items),
        }

        batch_fields: Dict[str, Any] = {
            "constraint_id": CONSTRAINT_CODE_SAFE if is_safe_all else CONSTRAINT_CODE_UNSAFE,
            "is_safe": is_safe_all,
            "is_valid": is_safe_all,
            "results": items,
            "summary": summary,
            "engine": "CodeVerifier-Pattern-Scanner",
        }

        # Batch proof must bind the complete inputs. Retain a digest of each
        # full snippet (proof-bearing) alongside truncated display text.
        snippet_digests: List[str] = []
        display_snippets: List[str] = []
        for snippet in snippets:
            raw = snippet.get("code", "")
            display_snippets.append(raw[:100] + "..." if len(raw) > 100 else raw)
            snippet_digests.append(hashlib.sha256(raw.encode("utf-8")).hexdigest())

        evidence = {
            "engine": "CodeVerifier-Pattern-Scanner",
            "count": total,
            "snippets": display_snippets,
            "snippet_digests": snippet_digests,
            "is_safe": is_safe_all,
            "verdicts": [
                {"status": item["status"], "is_valid": item["developer_fields"].get("is_valid")}
                for item in items
            ],
        }

        if is_safe_all:
            agent_message = "Batch code verification succeeded: all snippets passed security checks."
        else:
            agent_message = "Batch code verification flagged unsafe snippets; the batch is not admissible."

        return DiagnosticResult.verified(
            agent_message=agent_message,
            developer_fields=batch_fields,
            evidence=evidence,
        )

    def to_verification_context(self, result: "DiagnosticResult", query: str, attestation_token: Optional[str] = None) -> "VerificationContextDocument":
        """Map a DiagnosticResult to a Verification Context v1.0 document."""
        from .verification_context_bridge import verification_context_from_diagnostic_result
        return verification_context_from_diagnostic_result(
            result,
            formal_statement=query,
            attestation_token=attestation_token,
            verifier="CodeVerifier",
        )



